openapi: 3.0.0
info:
  title: API de Adopción de Mascotas
  description: Documentación de la API del sistema de adopciones.
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Servidor local

paths:
  /users:
    get:
      summary: Obtener todos los usuarios
      description: Retorna una lista de todos los usuarios registrados.
      responses:
        "200":
          description: Lista de usuarios obtenida correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    email:
                      type: string

  /adoptions:
    get:
      summary: Obtener todas las adopciones
      description: Retorna una lista de todas las solicitudes de adopción.
      responses:
        "200":
          description: Lista de adopciones obtenida correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    pet:
                      type: string
                    adopter:
                      type: string
                    status:
                      type: string
